platform:
  - x64
  - x86

configuration:
  #- Debug
  - Release

environment:
  CMAKE: cmake.exe
  
  matrix:
    - CXXLIB: 
    - CXXLIB: libc++

matrix:
  fast_finish: true   # set this flag to immediately finish build once one of the jobs fails.

  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

skip_tags: true
os:
  - Visual Studio 2015

build:
  parallel: true
  verbosity: detailed

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat

build_script:
- tools\packaging\cpt.py --current-dev=tar --with-cling-url=https://github.com/vgvassilev/cling --verbose

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_failure:
# Your RDP session is limited by overall build time (60 min).
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
